### ISSUE TITLE
got issue on converting

### ISSUE THREAD

**Issue by tshrinivasan** [Sathishsathi/epub2html#1]
Book url - https://freetamilebooks.com/ebooks/some_months_in_england/

python3 write_html.py some_months_in_england.epub some_months_in_england
Unknown error occured
Traceback (most recent call last):
  File "write_html.py", line 42, in write_html_file
    im.save(os.path.join(os.getcwd(), folder, file_name))
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2099, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/home/shrini/dev/epub2html/some_months_in_england/media/cover.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "write_html.py", line 96, in <module>
    write_html_file(book, folder_name)
  File "write_html.py", line 86, in write_html_file
    print(traceback.format_exc())
NameError: name 'traceback' is not defined

**Comment by Sathishsathi** [comment]
Added media folder inside the Template01. Since that was a empty folder, while doing a push, it is not added in the repo. Now you can try with the same command.
